package com.jazzify.backend.shared.domain;

public enum MusicKey {
    // C
    C_MAJOR, C_SHARP_MAJOR, C_FLAT_MAJOR,
    C_MINOR, C_SHARP_MINOR, C_FLAT_MINOR,
    // D
    D_MAJOR, D_SHARP_MAJOR, D_FLAT_MAJOR,
    D_MINOR, D_SHARP_MINOR, D_FLAT_MINOR,
    // E
    E_MAJOR, E_SHARP_MAJOR, E_FLAT_MAJOR,
    E_MINOR, E_SHARP_MINOR, E_FLAT_MINOR,
    // F
    F_MAJOR, F_SHARP_MAJOR, F_FLAT_MAJOR,
    F_MINOR, F_SHARP_MINOR, F_FLAT_MINOR,
    // G
    G_MAJOR, G_SHARP_MAJOR, G_FLAT_MAJOR,
    G_MINOR, G_SHARP_MINOR, G_FLAT_MINOR,
    // A
    A_MAJOR, A_SHARP_MAJOR, A_FLAT_MAJOR,
    A_MINOR, A_SHARP_MINOR, A_FLAT_MINOR,
    // B
    B_MAJOR, B_SHARP_MAJOR, B_FLAT_MAJOR,
    B_MINOR, B_SHARP_MINOR, B_FLAT_MINOR
}

